variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

stages:
  - build
  - verify
  - test

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - cd Client
    - mvn compile
    
verify:
  stage: verify
  script:
    - cd Client 
    - mvn clean verify

test:
  stage: test
  script:
    - cd Client
    - mvn test
    

    