variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

stages:
  - build-client
  - verify-client
  - test-client
  - build-server
  - verify-server
  - test-server
  - build-dataserver
  - verify-dataserver
  - test-dataserver

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build-client
  script:
    - cd Client
    - mvn compile
    
verify:
  stage: verify-client
  script:
    - cd Client 
    - mvn clean verify

test:
  stage: test-client
  script:
    - cd Client
    - mvn test
    
build:
  stage: build-server
  script:
    - cd Client
    - mvn compile
    
verify:
  stage: verify-server
  script:
    - cd Client 
    - mvn clean verify

test:
  stage: test-server
  script:
    - cd Client
    - mvn test
    
build:
  stage: build-dataserver
  script:
    - cd Client
    - mvn compile
    
verify:
  stage: verify-dataserver
  script:
    - cd Client 
    - mvn clean verify

test:
  stage: test-dataserver
  script:
    - cd Client
    - mvn test