package Server.SharedClientModels;

public enum MessageType
{
    LOGIN, SELL_ITEM, CALCULATE_ITEM_PRICE, REGISTER, GENERATE_NEW_WEAPON, HEARTBEAT, DELETE_ITEM_FROM_BACKPACK, LOGOUT, GET_MARKET_OFFERS, CANCEL_OFFER, GET_BACKPACK_ITEMS
}